spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: # https://<your-tenant-initial-domain-name>.b2clogin.com/<your-tenant-initial-domain-name>.onmicrosoft.com/
          credential:
            client-id: # application id
            client-secret: 'secret-value'
          login-flow: sign-up-or-sign-in
          logout-success-url: # logout url --> frontend/login-page
          user-flows:
            sign-up-or-sign-in: # <your-sign-up-or-sign-in-user-flow-name>
            profile-edit: # <your-profile-edit-user-flow-name> (optional)
            password-reset: # <your-password-reset-user-flow-name> (optional)
          user-name-attribute-name: # <your-user-name-attribute-name>